edition = "2024"
max_width = 100
use_small_heuristics = "Max"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
wrap_comments = true
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
normalize_comments = true
normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
match_block_trailing_comma = true
trailing_comma = "Vertical"
overflow_delimited_expr = true
error_on_line_overflow = false
error_on_unformatted = false
